## Numpy Functions

In [1]:
import numpy as np
arr = np.arange(10)
print(arr)
arr = np.random.rand(2, 3)
print(arr)
arr = np.arange(12)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
arr_concatenated = np.concatenate((arr1, arr2), axis=0)
print(arr_concatenated)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
mean_all = np.mean(arr)
print("Mean of the entire array:", mean_all)
sum_all = np.sum(arr)
print("Sum of the entire array:", sum_all)
max_val = np.max(arr)
print("Maximum value of the entire array:", max_val)
min_val = np.min(arr)
print("Minimum value of the entire array:", min_val)
std_all = np.std(arr)
print("Standard deviation of the entire array:", std_all)

[0 1 2 3 4 5 6 7 8 9]
[[0.05240294 0.50452077 0.56448273]
 [0.26757126 0.18575655 0.61855104]]
[[1 2]
 [3 4]
 [5 6]]
Mean of the entire array: 3.5
Sum of the entire array: 21
Maximum value of the entire array: 6
Minimum value of the entire array: 1
Standard deviation of the entire array: 1.707825127659933
